version: 2

seeds:
  - name: employees
    description: A manual amp of employees to customers
    columns:
      - name: employee_id
        tests:
            - unique
            - not_null 